---
swagger: "2.0"
info:
  version: "1.2"
  title: "Source DC API"
host: "example.source.example"
basePath: "/api/1.2/source_flow"
paths:
  /datarequest:
    get:
      tags:
      - "Source"
      description: "End point that receives data request from sink. Contains PoP in Authorization field in Header"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "PoP-token"
        description: "Authorization Token"
        required: true
        type: string

      responses:
        200:
          description: "Returns 200"
          schema:
            $ref: "#/definitions/data"
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"

definitions:
  errors:
      type: object
      properties:
        status:
          type: string
          description: HTTP status code as string value.
        code:
          type: integer
          description: HTTP status code
        title:
          type: string
          description: Title of error message.
        detail:
          type: string
          description: Detailed error message.
        source:
          type: string
          description: Source URI

  data:
      type: object

