-- MySQL Script generated by MySQL Workbench
-- to 15. syyskuuta 2016 15.37.01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_Service_Mockup
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_Service_Mockup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_Service_Mockup` DEFAULT CHARACTER SET latin1 ;
USE `db_Service_Mockup` ;

-- -----------------------------------------------------
-- Table `db_Service_Mockup`.`code_and_user_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_Service_Mockup`.`code_and_user_mapping` ;

CREATE TABLE IF NOT EXISTS `db_Service_Mockup`.`code_and_user_mapping` (
  `code` LONGTEXT NOT NULL,
  `user_id` LONGTEXT NOT NULL,
  PRIMARY KEY (`code`(255)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_Service_Mockup`.`storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_Service_Mockup`.`storage` ;

CREATE TABLE IF NOT EXISTS `db_Service_Mockup`.`storage` (
  `ID` LONGTEXT NOT NULL,
  `json` LONGTEXT NOT NULL,
  PRIMARY KEY (`ID`(255)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_Service_Mockup`.`surrogate_and_user_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_Service_Mockup`.`surrogate_and_user_mapping` ;

CREATE TABLE IF NOT EXISTS `db_Service_Mockup`.`surrogate_and_user_mapping` (
  `user_id` LONGTEXT NOT NULL,
  `surrogate_id` LONGTEXT NOT NULL,
  PRIMARY KEY (`user_id`(255)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE USER 'serviceMockup'@'%' IDENTIFIED BY 'MynorcA';
GRANT CREATE TEMPORARY TABLES, DELETE, DROP, INSERT, LOCK TABLES, SELECT, UPDATE ON db_Service_Mockup.* TO 'serviceMockup'@'%';
FLUSH PRIVILEGES;
