-- MySQL Script generated by MySQL Workbench
-- to 15. syyskuuta 2016 14.58.51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_Srv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_Srv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_Srv` DEFAULT CHARACTER SET utf8 ;
USE `db_Srv` ;

-- -----------------------------------------------------
-- Table `db_Srv`.`codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_Srv`.`codes` ;

CREATE TABLE IF NOT EXISTS `db_Srv`.`codes` (
  `ID` LONGTEXT NOT NULL,
  `code` LONGTEXT NOT NULL,
  PRIMARY KEY (`ID`(255)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_Srv`.`cr_storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_Srv`.`cr_storage` ;

CREATE TABLE IF NOT EXISTS `db_Srv`.`cr_storage` (
  `cr_id` LONGTEXT NOT NULL,
  `json` LONGTEXT NOT NULL,
  `slr_id` LONGTEXT NOT NULL,
  `surrogate_id` LONGTEXT NOT NULL,
  `rs_id` LONGTEXT NOT NULL,
  PRIMARY KEY (`cr_id`(255)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_Srv`.`csr_storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_Srv`.`csr_storage` ;

CREATE TABLE IF NOT EXISTS `db_Srv`.`csr_storage` (
  `cr_id` VARCHAR(255) NOT NULL,
  `csr_id` VARCHAR(255) NOT NULL,
  `previous_record_id` VARCHAr(255) NOT NULL,
  `consent_status` VARCHAR(10) NOT NULL,
  `json` LONGTEXT NOT NULL,
  `slr_id` LONGTEXT NOT NULL,
  `surrogate_id` LONGTEXT NOT NULL,
  `rs_id` LONGTEXT NOT NULL,
  PRIMARY KEY (`csr_id`(255)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_Srv`.`storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_Srv`.`storage` ;

CREATE TABLE IF NOT EXISTS `db_Srv`.`storage` (
  `surrogate_id` LONGTEXT NOT NULL,
  `json` LONGTEXT NOT NULL,
  PRIMARY KEY (`surrogate_id`(255)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_Srv`.`token_storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_Srv`.`token_storage` ;

CREATE TABLE IF NOT EXISTS `db_Srv`.`token_storage` (
  `cr_id` LONGTEXT NOT NULL,
  `token` LONGTEXT NOT NULL,
  PRIMARY KEY (`cr_id`(255)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
CREATE USER 'service'@'%' IDENTIFIED BY 'MynorcA';
GRANT CREATE TEMPORARY TABLES, DELETE, DROP, INSERT, LOCK TABLES, SELECT, UPDATE ON db_Srv.* TO 'service'@'%';
FLUSH PRIVILEGES;